meta_title: "Cooodit | Ateliers numériques pour enfants"
meta_description: "Venez découvrir le campus cooodit et ses ateliers de programmation et code informatique pour les enfants de 7 à 17 ans tout au long de l'année scolaire"
meta_image: "cover-2.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@Cooodit"